name: camouflage-detection
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - opencv
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - tqdm
  - pyyaml
  - pip
  - pip:
    - ultralytics
    - streamlit
